plugins {
    java
}

group = "com.myiui"
version = "1.0.0"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

repositories {
    mavenCentral()
}

val javacvVersion = "1.5.11"
val ffmpegVersion = "6.1.1-$javacvVersion"

dependencies {
    compileOnly("org.ow2.asm:asm:9.7.1")
    compileOnly("org.ow2.asm:asm-commons:9.7.1")
    // win-x64 release only — avoid javacv-platform (~600MB all-OS natives)
    implementation("org.bytedeco:javacv:$javacvVersion") {
        exclude(group = "org.bytedeco", module = "ffmpeg-platform")
        exclude(group = "org.bytedeco", module = "openblas-platform")
        exclude(group = "org.bytedeco", module = "opencv-platform")
    }
    implementation("org.bytedeco:ffmpeg:$ffmpegVersion")
    runtimeOnly("org.bytedeco:ffmpeg:$ffmpegVersion:windows-x86_64")
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("com.google.zxing:core:3.5.3")
    implementation("com.google.zxing:javase:3.5.3")
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "com.myiui.agent.Main",
            "Implementation-Title" to "MyiUI Agent",
            "Implementation-Version" to project.version,
            "Implementation-License" to "AGPL-3.0"
        )
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
}

// Generate preloader_class.h from AgentBootstrap.class — pure Java, no PowerShell needed
tasks.register("generatePreloaderHeader") {
    dependsOn(tasks.classes)
    val outFile = rootProject.file("../overlay/src/preload/preloader_class.h")
    val classFile = layout.buildDirectory.file("classes/java/main/com/myiui/preload/AgentBootstrap.class")
    outputs.file(outFile)
    doLast {
        val classPath = classFile.get().asFile
        if (!classPath.exists()) {
            throw GradleException("Class file not found: ${classPath.absolutePath}")
        }
        val bytes = classPath.readBytes()
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by Gradle — do not edit.")
        sb.appendLine("#pragma once")
        sb.appendLine()
        sb.appendLine("#include <cstddef>")
        sb.appendLine("#include <cstdint>")
        sb.appendLine()
        sb.appendLine("inline constexpr std::size_t preloader_classSizes = ${bytes.size};")
        sb.append("inline const unsigned char preloader_class[] = {")
        for (i in bytes.indices) {
            if (i % 16 == 0) {
                sb.appendLine()
                sb.append("    ")
            }
            sb.append("0x%02X".format(bytes[i].toInt() and 0xFF))
            if (i < bytes.size - 1) sb.append(", ")
        }
        sb.appendLine()
        sb.appendLine("};")
        sb.appendLine()
        outFile.parentFile.mkdirs()
        outFile.writeText(sb.toString(), Charsets.UTF_8)
        println("Wrote ${outFile.absolutePath} (${bytes.size} bytes)")
    }
}

tasks.named("jar") {
    dependsOn("generatePreloaderHeader")
}
